[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "versioneer-518"
]
build-backend = "setuptools.build_meta"

[project.optional_dependencies]
tests= [
    "pytest",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -s"
testpaths = [
    "tests",
]
